AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Stack for lmd-s3-cloudfront-resizing-origin-request Lambda Function'.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10  # Default value: 3 seconds
    MemorySize: 1024
    Handler: index.handler
    Architectures:
      - x86_64

Parameters:
  LambdaFunctionName:
    Type: String
    Default: lmd-s3-cloudfront-resizing-origin-request
    Description: The name of the Lambda function.

Resources:
  AwsLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Ref LambdaFunctionName
      CodeUri: functions/lmd-sample-function/
      Handler: index.handler
      Runtime: nodejs20.x
      Description: >
        lmd-s3-cloudfront-resizing-origin-request Lambda Function'.
      Role: arn:aws:iam::xxxx:role/duck's role
      AutoPublishAlias: live

Outputs:
  LambdaFunctionVersion:
    Description: The version ARN of the Lambda function
    Value: !Ref AwsLambdaFunction.Version
